### ISSUE TITLE
User `postgresql` does not exist

### ISSUE THREAD

**Issue by chris-aeviator** [Sen2Agri/Sen2Agri-System#37]
When installing Sen2Agri from scratch on centos 7 the install script will show many errors:

```
Executing SQL script: ./database/07-data/04.job_start_type.sql                                                                 │
su: user postgres does not exist
```

I can connect to psql via `psql -U postgres -d sen2agri`

**Comment by lnicola** [comment]
I assume you're using one of the released installation packages? This is probably caused by a previous change that moved the database to a Docker container. The installation script you're using might not have been updated for it -- there's no more `postgres` system user. The current version of the script simply does `psql -U postgres`, which works: https://github.com/Sen2Agri/Sen2Agri-System/blob/master/install_platform/sen2agriPlatformInstallAndConfig.sh#L429.

**Comment by chris-aeviator** [comment]
I can confirm I can connect to my db via `sudo psql -U postgres`
